library(data.table)
tumor=data.frame(fread("E:/Projects/Proteogenomic_PROMIX/Manuscript/Revision/Analyses/Figure3/GSE62944_RAW/GSM1536837_06_01_15_TCGA_24.tumor_Rsubread_TPM.txt/GSM1536837_06_01_15_TCGA_24.tumor_Rsubread_TPM.txt"),row.names=1)
normal=data.frame(fread("E:/Projects/Proteogenomic_PROMIX/Manuscript/Revision/Analyses/Figure3/GSE62944_RAW/GSM1697009_06_01_15_TCGA_24.normal_Rsubread_TPM.txt/GSM1697009_06_01_15_TCGA_24.normal_Rsubread_TPM.txt"),row.names=1)
tumor_meta=data.frame(fread("E:/Projects/Proteogenomic_PROMIX/Manuscript/Revision/Analyses/Figure3/GSE62944_06_01_15_TCGA_24_CancerType_Samples.txt/GSE62944_06_01_15_TCGA_24_CancerType_Samples.txt"))
colnames(tumor_meta)=c("sampleID","type")
tumor_meta$sampleID=gsub("-", ".", tumor_meta$sampleID)
normal_meta=data.frame(fread("E:/Projects/Proteogenomic_PROMIX/Manuscript/Revision/Analyses/Figure3/GSE62944_06_01_15_TCGA_24_Normal_CancerType_Samples.txt/GSE62944_06_01_15_TCGA_24_Normal_CancerType_Samples.txt"))
colnames(normal_meta)=c("sampleID","type")
normal_meta$sampleID=gsub("-", ".", normal_meta$sampleID)
tumor_brca=tumor[,tumor_meta$sampleID[tumor_meta$type=="BRCA"]]
tumor_brca=log2(tumor_brca+1)
normal_brca=normal[,normal_meta$sampleID[normal_meta$type=="BRCA"]]
normal_brca=log2(normal_brca+1)
saveRDS(tumor_brca[,1:30],file="E:/R_Dev/PureMeta/data/TCGA_BRCA_log2TPM.rds")
saveRDS(normal_brca[,1:10],file="E:/R_Dev/PureMeta/data/TCGA_normal_breast_log2TPM.rds")
